bulbs:
    # - ip: 192.168.1.3   # escritorio
    #   min_temp: 2700
    #   max_temp: 6000
    # - ip: 192.168.10.4 # office
    #   min_temp: 2700
    #   max_temp: 6000
    - ip: 192.168.10.5    # sala
      min_temp: 2700
      max_temp: 6000
    # - ip: 192.168.1.16
    #   min_temp: 2700
    #   max_temp: 6000
